### ISSUE TITLE
Draws 1 extra pixel on the bottom mask?

### ISSUE THREAD

**Issue by obigal** [a1k0n/arduboy3d#1]
Totally not important the last commit was years ago but I'm curious if this was by design? 

https://github.com/a1k0n/arduboy3d/blob/013f58d51dc66caffb7ecf35c172543caede9b0a/draw.cpp#L18

This seems correct.
`const uint8_t bottommask_[] PROGMEM = {
  0x00, 0x01, 0x03, 0x07, 0x0f, 0x1f, 0x3f, 0x7f
};`

**Comment by a1k0n** [comment]
Hmm. Yeah, not fresh in my mind. I think that's intentional, though; I guess it's not documented, but when I read the code now it seems that FillVLine is supposed to fill from y0 to y1, inclusive.

https://github.com/a1k0n/arduboy3d/blob/013f58d51dc66caffb7ecf35c172543caede9b0a/draw.cpp#L294-L299

It looks like I subtract 1 from the bottom to not include it, according to that comment. So if y0==y1, it should plot one pixel.

**Comment by obigal** [comment]
Got it. Thanks! I couldn't work out how that was implemented.

**Comment by a1k0n** [comment]
:+1:
